### ISSUE TITLE
Dimension mismatch between ground truth mask and predicted image

### ISSUE THREAD

**Issue by z-mahmud22** [yzslab/gaussian-splatting-lightning#24]
Hi @yzslab, thank you for this amazing work! 

I was testing out the Dynamic mask feature from this repo. I have 33 rgb images and their corresponding masks both having the same image dimension of `[1920 x 1080]`. I used this command to run GS with dynamic masking:
```
python main.py fit --data.path <path_to_COLMAP_data> --data.params.colmap.mask_dir <path_to_mask> -n <exp_name>
```
However, each time, I'm encountering the following error:
```
File "C:\Users\user\gs_lightning\internal\gaussian_splatting.py", line 169, in forward_with_loss_calculation
    gt_image[masked_pixels] = image.detach()[masked_pixels]  # copy masked pixels from prediction to G.T.
IndexError: The shape of the mask [3, 1920, 1080] at index 1 does not match the shape of the indexed tensor [3, 1919, 1080] at index 1
```

I checked from the terminal that it read all the images and the masks: `[colmap dataparser] train set images: 33, val set images: 5, loaded mask: 33`. I also checked the dimensions of `masked_pixels`, `gt_image` and `image` at this [line](https://github.com/yzslab/gaussian-splatting-lightning/blob/87d559d20801a455ce1ea4ebc77e3be813a0e1e0/internal/gaussian_splatting.py#L167) which are: 
```
gt_image shape torch.Size([3, 1920, 1080])
masked_pixels shape torch.Size([3, 1920, 1080])
image shape torch.Size([3, 1919, 1080])
```
Looks like the rendered image from [`image = outputs["render"]`](https://github.com/yzslab/gaussian-splatting-lightning/blob/87d559d20801a455ce1ea4ebc77e3be813a0e1e0/internal/gaussian_splatting.py#L163C9-L163C34) somehow, getting a different resolution. Here's the complete traceback if it helps:
```
Traceback (most recent call last):
  File "C:\Users\user\gs_lightning\main.py", line 37, in <module>
    cli_main()
  File "C:\Users\user\gs_lightning\main.py", line 12, in cli_main
    cli = CLI(
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\cli.py", line 359, in __init__
    self._run_subcommand(self.subcommand)
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\cli.py", line 650, in _run_subcommand
    fn(**fn_kwargs)
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\trainer\call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 980, in _run
    results = self._run_stage()
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1021, in _run_stage
    self._run_sanity_check()
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\trainer\trainer.py", line 1050, in _run_sanity_check
    val_loop.run()
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\loops\utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\loops\evaluation_loop.py", line 376, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\trainer\call.py", line 294, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\gspl\lib\site-packages\lightning\pytorch\strategies\strategy.py", line 393, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "C:\Users\user\gs_lightning\internal\gaussian_splatting.py", line 332, in validation_step
    outputs, loss, rgb_diff_loss, ssim_metric = self.forward_with_loss_calculation(camera, image_info)
  File "C:\Users\user\gs_lightning\internal\gaussian_splatting.py", line 169, in forward_with_loss_calculation
    gt_image[masked_pixels] = image.detach()[masked_pixels]  # copy masked pixels from prediction to G.T.
IndexError: The shape of the mask [3, 1920, 1080] at index 1 does not match the shape of the indexed tensor [3, 1919, 1080] at index 1
```
I am wondering if you could give some idea about this issue. 

I used this same dataset with your previous [fork](https://github.com/yzslab/gaussian-splatting/tree/dynamic_mask) and could run the optimization without any issue.

**Comment by yzslab** [comment]
Are you using the images that undistorted by colmap? The image shape may be
changed after undistortion.
You should use same parameters to undistorte mask images too.

**Comment by z-mahmud22** [comment]
Thank you for such a quick response! You're right, it seems COLMAP some times downsize the images as part of undistortion process and hence the image dimension mismatch between the masks and the undistorted images. 

However, I could not extract the distortion parameters from COLMAP to undistort the masks. I checked the `database.db` file but it does not contain the distortion coefficients. As a [workaround](https://github.com/colmap/colmap/issues/2282#issuecomment-2050291426), I'm currently setting `--min_scale 1.0` during undistortion to keep the resolution of the undistorted images same as the original ones. 

Please feel free to suggest a better approach if there's one, or you can close this issue.

**Comment by yzslab** [comment]
> Thank you for such a quick response! You're right, it seems COLMAP some times downsize the images as part of undistortion process and hence the image dimension mismatch between the masks and the undistorted images.
> 
> However, I could not extract the distortion parameters from COLMAP to undistort the masks. I checked the `database.db` file but it does not contain the distortion coefficients. As a [workaround](https://github.com/colmap/colmap/issues/2282#issuecomment-2050291426), I'm currently setting `--min_scale 1.0` during undistortion to keep the resolution of the undistorted images same as the original ones.
> 
> Please feel free to suggest a better approach if there's one, or you can close this issue.

You can find distortion parameters in `cameras.bin`.
Here is the code that I used to undistort mask images, hoping it can provide you some help:
```python
"""
using colmap sparse model to undistort images that not in the database,
auto select camera based on the dirname,
"""

import os
import time
import random
import argparse
import pathlib
import numpy as np
import cv2
import tqdm
import internal.colmap.read_write_model  # https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py
import multiprocessing.pool

parser = argparse.ArgumentParser()
parser.add_argument("--model-dir", "-m", type=str, required=True)
parser.add_argument("--mask-path", "--src", type=str, required=True)
parser.add_argument("--output-path", "--dst", type=str, default=None)
parser.add_argument("--max-size", type=int, default=-1)
parser.add_argument("--extension", "-e", type=str, default="png")
parser.add_argument("--no-single-channel", action="store_true", default=False)
args = parser.parse_args()

cameras = internal.colmap.read_write_model.read_cameras_binary(os.path.join(args.model_dir, "cameras.bin"))
images = internal.colmap.read_write_model.read_images_binary(os.path.join(args.model_dir, "images.bin"))

# build camera param string dict
camera_param_string_key_by_camera_id = {}
for idx in cameras:
    camera = cameras[idx]
    camera_param_string = "{} {} {} {}".format(
        camera.model,
        camera.width,
        camera.height,
        " ".join([str(i) for i in camera.params])
    )
    camera_param_string_key_by_camera_id[idx] = camera_param_string

# build image dir to camera id dict
camera_id_key_by_dirname = {}
for idx in images:
    image = images[idx]
    dirname = os.path.dirname(image.name.strip("/"))
    camera_id_key_by_dirname[dirname] = image.camera_id

mask_path = pathlib.Path(args.mask_path)
output_path = args.output_path
if output_path is None:
    output_path = "{}_undistorted".format(args.mask_path)
os.makedirs(output_path, exist_ok=True)

txt_file_path = "/tmp/image_undistorter_standalone-{}-{}.txt".format(
    int(time.time()),
    int(random.random() * 10000)
)
with open(txt_file_path, "w") as f:
    with tqdm.tqdm(mask_path.rglob("*.{}".format(args.extension))) as t:
        for filename in t:
            relative_dirname = os.path.dirname(str(filename).replace(args.mask_path, "")).strip("/")
            if (relative_dirname in camera_id_key_by_dirname) is False:
                print("{} not found in mask path".format(relative_dirname))
                continue
            camera_id = camera_id_key_by_dirname[relative_dirname]
            camera_param_string = camera_param_string_key_by_camera_id[camera_id]

            filename = str(filename).replace(args.mask_path, "").lstrip("/")
            os.makedirs(os.path.join(output_path, os.path.dirname(filename)), exist_ok=True)
            t.set_description(filename)
            f.write("{} {}\n".format(
                filename,
                camera_param_string
            ))

print(txt_file_path)

pid = os.fork()
if pid == 0:
    os.execvp("colmap", [
        "colmap",
        "image_undistorter_standalone",
        "--input_file",
        txt_file_path,
        "--image_path",
        args.mask_path,
        "--output_path",
        output_path,
        "--max_image_size",
        str(args.max_size),
    ])
    exit(-1)

_, status = os.wait()
if status != 0:
    exit(status)

if args.no_single_channel is True:
    exit(0)


def to_single_channel(filename):
    filename = str(filename)
    mask = cv2.imread(filename, cv2.IMREAD_UNCHANGED)
    if mask.shape[-1] != 3:
        return
    mask = (mask[:, :, 0] > 0).astype(np.uint8) * 255
    cv2.imwrite(filename, mask)


tasks = list(pathlib.Path(args.output_path).rglob("*.png"))
with multiprocessing.pool.ThreadPool() as pool:
    for _ in tqdm.tqdm(pool.imap_unordered(to_single_channel, tasks), total=len(tasks)):
        pass
```

**Comment by yzslab** [comment]
I have made some modification to the code above, and added to this repository: https://github.com/yzslab/gaussian-splatting-lightning/blob/main/utils/colmap_undistort_mask.py
