### ISSUE TITLE
Error using Renderer

### ISSUE THREAD

**Issue by SamPease** [yzslab/gaussian-splatting-lightning#38]
I used the viewer to create a render path and exported the command. Upon running the command:

python render.py outputs/video1/seganygs --camera-path-filename /home/spease/EIOR_working/eoir_tasks/spease/gaussian-splatting-lightning/camera_paths/2024-07-15-13-19-02.json --output-path renders//2024-07-15-13-19-02.mp4

I get the following error:

/home/spease/EIOR_working/eoir_venv/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/home/spease/EIOR_working/eoir_tasks/spease/gaussian-splatting-lightning/render.py", line 230, in <module>
    renderer = initializer_viewer_renderer(
  File "/home/spease/EIOR_working/eoir_tasks/spease/gaussian-splatting-lightning/render.py", line 36, in initializer_viewer_renderer
    model, renderer = GaussianModelLoader.search_and_load(model_path, sh_degree, load_device)
  File "/home/spease/EIOR_working/eoir_tasks/spease/gaussian-splatting-lightning/internal/utils/gaussian_model_loader.py", line 85, in search_and_load
    model, renderer, _ = cls.initialize_simplified_model_from_checkpoint(load_from, device=device)
  File "/home/spease/EIOR_working/eoir_tasks/spease/gaussian-splatting-lightning/internal/utils/gaussian_model_loader.py", line 53, in initialize_simplified_model_from_checkpoint
    sh_degree = hparams["gaussian"].sh_degree
KeyError: 'gaussian'

**Comment by yzslab** [comment]
Hi, I have not implemented video rendering for SegAnyGS.
