### ISSUE TITLE
how can i use multiple metrics?

### ISSUE THREAD

**Issue by insomniaaac** [yzslab/gaussian-splatting-lightning#59]
i used depth anything reg, all worked great!
but then i want to add mcmc along with depth reg, so my config.yaml like
```yaml
data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  parser: internal.dataparsers.estimated_depth_colmap_dataparser.EstimatedDepthColmap
model:
  renderer: internal.renderers.mip_splatting_gsplat_renderer.MipSplattingGSplatRenderer
  metric: 
    - internal.metrics.inverse_depth_metrics.HasInverseDepthMetrics
    - internal.metrics.mcmc_metrics.MCMCMetrics
  renderer_output_types:
    - rgb
    - inverse_depth
  density: internal.density_controllers.mcmc_density_controller.MCMCDensityController
  density: 
    absgrad: true
cache_all_images: true
```
expect to use mip splat, depth reg and mcmc.

but i got errors below
```
main.py [options] fit: error: Parser key "model.metric":
  Not a valid subclass of Metric. Got value: ['internal.metrics.inverse_depth_metrics.HasInverseDepthMetrics', 'internal.metrics.mcmc_metrics.MCMCMetrics']
  Subclass types expect one of:
  - a class path (str)
  - a dict with class_path entry
  - a dict without class_path but with init_args entry (class path given previously)
  ```
can i use multiple metrics?

**Comment by yzslab** [comment]
Only single instance is allowed. You need you write your own one if you want to combine them.

**Comment by insomniaaac** [comment]
i write a metric try to combine depth reg and mcmc metric,
```python
# depth_mcmc_metrics.py

from typing import Literal, Tuple, Dict, Any
from dataclasses import dataclass, field
import torch
from torchmetrics.image import StructuralSimilarityIndexMeasure
from .vanilla_metrics import VanillaMetrics, VanillaMetricsImpl


@dataclass
class WeightScheduler:
    init: float = 1.0

    final_factor: float = 0.01

    max_steps: int = 30_000


@dataclass
class DepthMCMCMetrics(VanillaMetrics):
    # depth
    depth_loss_type: Literal["l1", "l2", "kl"] = "l1"

    depth_loss_ssim_weight: float = 0.2
    
    depth_loss_weight: WeightScheduler = field(default_factory=lambda: WeightScheduler())

    depth_normalized: bool = False

    depth_output_key: str = "inverse_depth"
    
    # mcmc
    
    opacity_reg: float = 0.01

    scale_reg: float = 0.01

    def instantiate(self, *args, **kwargs) -> "DepthMCMCMetricsModule":
        return DepthMCMCMetricsModule(self)


class DepthMCMCMetricsModule(VanillaMetricsImpl):
    config: DepthMCMCMetrics

    def setup(self, stage: str, pl_module):
        super().setup(stage, pl_module)

        if self.config.depth_loss_type == "l1":
            self._get_inverse_depth_loss = self._depth_l1_loss
        elif self.config.depth_loss_type == "l1+ssim":
            self.depth_ssim = StructuralSimilarityIndexMeasure()
            self._get_inverse_depth_loss = self._depth_l1_and_ssim_loss
        elif self.config.depth_loss_type == "l2":
            self._get_inverse_depth_loss = self._depth_l2_loss
        # elif self.config.depth_loss_type == "kl":
        #     self._get_inverse_depth_loss = self._depth_kl_loss
        else:
            raise NotImplementedError()

    def _depth_l1_loss(self, a, b):
        return torch.abs(a - b).mean()
    
    def _depth_l1_and_ssim_loss(self, a, b):
        l1_loss = self._depth_l1_loss(a, b)
        ssim_metric = self.depth_ssim(a[None, None, ...], b[None, None, ...])

        return (1 - self.config.depth_loss_ssim_weight) * l1_loss + self.config.depth_loss_ssim_weight * (1 - ssim_metric)


    def _depth_l2_loss(self, a, b):
        return ((a - b) ** 2).mean()

    def _depth_kl_loss(self, a, b):
        pass

    def get_inverse_depth_metric(self, batch, outputs):
        # TODO: apply mask

        camera, _, gt_inverse_depth = batch

        if gt_inverse_depth is None:
            return torch.tensor(0., device=camera.device)

        predicted_inverse_depth = outputs[self.config.depth_output_key].squeeze(0)
        if self.config.depth_normalized:
            with torch.no_grad():
                max_depth = predicted_inverse_depth.max()
                min_depth = predicted_inverse_depth.min()
            predicted_inverse_depth = (predicted_inverse_depth - min_depth) / (max_depth - min_depth + 1e-8)

        if isinstance(gt_inverse_depth, tuple):
            gt_inverse_depth, gt_inverse_depth_mask = gt_inverse_depth

            gt_inverse_depth = gt_inverse_depth * gt_inverse_depth_mask
            predicted_inverse_depth = predicted_inverse_depth * gt_inverse_depth_mask

        return self._get_inverse_depth_loss(gt_inverse_depth, predicted_inverse_depth)

    def get_weight(self, step: int):
        return self.config.depth_loss_weight.init * (self.config.depth_loss_weight.final_factor ** min(step / self.config.depth_loss_weight.max_steps, 1))
    
    def get_train_metrics(self, pl_module, gaussian_model, step: int, batch, outputs) -> Tuple[Dict[str, Any], Dict[str, bool]]:
        metrics, pbar = super().get_train_metrics(pl_module, gaussian_model, step, batch, outputs)

        d_reg_weight = self.get_weight(step)
        d_reg = self.get_inverse_depth_metric(batch, outputs) * d_reg_weight
        
        opacity_reg_loss = self.config.opacity_reg * torch.abs(gaussian_model.get_opacity).mean()
        scale_reg_loss = self.config.scale_reg * torch.abs(gaussian_model.get_scaling).mean()

        metrics["loss"] = metrics["loss"] + d_reg + opacity_reg_loss + scale_reg_loss
        metrics["d_reg"] = d_reg
        metrics["d_w"] = d_reg_weight
        metrics["o_reg"] = opacity_reg_loss
        metrics["s_reg"] = scale_reg_loss
        pbar["d_reg"] = True
        pbar["d_w"] = True
        pbar["o_reg"] = True
        pbar["s_reg"] = True

        return metrics, pbar

    def get_validate_metrics(self, pl_module, gaussian_model, batch, outputs) -> Tuple[Dict[str, float], Dict[str, bool]]:
        metrics, pbar = super().get_validate_metrics(pl_module, gaussian_model, batch, outputs)

        d_reg = self.get_inverse_depth_metric(batch, outputs)
        
        opacity_reg_loss = self.config.opacity_reg * torch.abs(gaussian_model.get_opacity).mean()
        scale_reg_loss = self.config.scale_reg * torch.abs(gaussian_model.get_scaling).mean()

        metrics["loss"] = metrics["loss"] + d_reg + opacity_reg_loss + scale_reg_loss
        metrics["d_reg"] = d_reg
        metrics["o_reg"] = opacity_reg_loss
        metrics["s_reg"] = scale_reg_loss
        pbar["d_reg"] = True
        pbar["o_reg"] = True
        pbar["s_reg"] = True

        return metrics, pbar
```
then my config.yaml is
```yaml
# common configuration
cache_all_images: true
max_steps: 500000
save_iterations:
- 7000
- 30000
- 50000

# dataset configuration
data:
  val_max_num_images_to_cache: -1
  test_max_num_images_to_cache: -1
  parser: internal.dataparsers.estimated_depth_colmap_dataparser.EstimatedDepthColmap

# model configuration
model:
  # gaussian model configuration
  gaussian: 
    class_path: internal.models.mip_splatting.MipSplatting

  # renderer configuration
  renderer: 
    class_path: internal.renderers.gsplat_mip_splatting_renderer_v2.GSplatMipSplattingRendererV2
  renderer_output_types:
    - rgb
    - hard_inverse_depth
  
  # metric configuration
  metric:
    class_path: internal.metrics.depth_mcmc_metrics.DepthMCMCMetrics
    init_args:
      depth_output_key: hard_inverse_depth
  
  # density controller configuration
  density: 
    class_path: internal.density_controllers.mcmc_density_controller.MCMCDensityController
    init_args:
      cap_max: 200000
      densify_until_iter: 40000
```

how ever i get error message like:
```text
Traceback (most recent call last):                                                                                                                                                                     
  File "/home/disk/gaussian-splatting-lightning/main.py", line 4, in <module>
    cli()
  File "/home/disk/gaussian-splatting-lightning/internal/entrypoints/gspl.py", line 12, in cli
    CLI(
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/cli.py", line 359, in __init__
    self._run_subcommand(self.subcommand)
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/cli.py", line 650, in _run_subcommand
    fn(**fn_kwargs)
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1023, in _run_stage
    self.fit_loop.run()
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 355, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 221, in advance
    batch_output = self.manual_optimization.run(kwargs)
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/manual.py", line 91, in run
    self.advance(kwargs)
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/manual.py", line 111, in advance
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 294, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/lightning/pytorch/strategies/strategy.py", line 380, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/home/disk/gaussian-splatting-lightning/internal/gaussian_splatting.py", line 380, in training_step
    self.density_controller.after_backward(
  File "/home/disk/gaussian-splatting-lightning/internal/density_controllers/mcmc_density_controller.py", line 86, in after_backward
    self.relocate_gs(gaussian_model, optimizers, dead_mask)
  File "/home/disk/gaussian-splatting-lightning/internal/density_controllers/mcmc_density_controller.py", line 201, in relocate_gs
    getattr(gaussian_model, attr_name)[dead_indices] = new_params[attr_name]
  File "/home/disk/miniconda3/envs/gspl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MipSplattingModel' object has no attribute 'filter_3d'
```

**Comment by yzslab** [comment]
Looks like the new MipSplatting model does not have the getters and setters required by MCMC.
Before it is fixed, try using `VanillaGaussianModel` together with [`MipSplattingGSplatRenderer`](https://github.com/yzslab/gaussian-splatting-lightning/blob/main/internal/renderers/mip_splatting_gsplat_renderer.py).

**Comment by yzslab** [comment]
Besides, I haven't add depth map rendering to both the v1 and v2 MipSplatting renderer.

**Comment by yzslab** [comment]
This path shoule be able to fix the exception you mentioned:
```diff
Index: internal/density_controllers/mcmc_density_controller.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/internal/density_controllers/mcmc_density_controller.py b/internal/density_controllers/mcmc_density_controller.py
--- a/internal/density_controllers/mcmc_density_controller.py	(revision 739c5decc76f71bf43a99eeef0e070a46f8b84e1)
+++ b/internal/density_controllers/mcmc_density_controller.py	(date 1726401020358)
@@ -198,7 +198,7 @@
 
         new_params = self._get_new_params(gaussian_model, reinit_idx, ratio=ratio)
         for attr_name in new_params:
-            getattr(gaussian_model, attr_name)[dead_indices] = new_params[attr_name]
+            gaussian_model.get_property(attr_name)[dead_indices] = new_params[attr_name]
 
         # update the opacities and scales of the sampled Gaussians too
         gaussian_model.opacities[reinit_idx] = gaussian_model.opacities[dead_indices]
```

**Comment by insomniaaac** [comment]
> Besides, I haven't add depth map rendering to both the v1 and v2 MipSplatting renderer.

thanks for quick reply!
i noticed that many renderers are developed based on `GSPlatRenderer`
can you give me some hint to add depth map rendering for mipsplatting renderer?

**Comment by yzslab** [comment]
> can you give me some hint to add depth map rendering for mipsplatting renderer?

Here is an example:
https://github.com/yzslab/gaussian-splatting-lightning/blob/739c5decc76f71bf43a99eeef0e070a46f8b84e1/internal/renderers/gsplat_appearance_embedding_renderer.py#L203-L225

**Comment by insomniaaac** [comment]
i implement depth map rendering by simply add codes you mentioned above.
```python
from dataclasses import dataclass

from typing import Any
import torch

from .renderer import RendererConfig, Renderer
from .gsplat_renderer import GSPlatRenderer
from ..cameras import Camera
from ..models.mip_splatting import MipSplattingModel


@dataclass
class GSplatMipSplattingRendererV2WithDepth(RendererConfig):
    filter_2d_kernel_size: float = 0.1

    def instantiate(self, *args, **kwargs) -> "GSplatMipSplattingRendererV2ModuleWithDepth":
        return GSplatMipSplattingRendererV2ModuleWithDepth(self)


class GSplatMipSplattingRendererV2ModuleWithDepth(Renderer):
    def __init__(self, config) -> None:
        super().__init__()
        self.config = config

    def setup(self, stage: str, lightning_module=None, *args: Any, **kwargs: Any) -> Any:
        self.renderer = GSPlatRenderer()

    def preprocess(self, pc, viewpoint_camera, scaling_modifier):
        return GSPlatRenderer.project(
            means3D=pc.get_xyz,
            scales=pc.get_scaling,
            rotations=pc.get_rotation,
            viewpoint_camera=viewpoint_camera,
            scaling_modifier=scaling_modifier,
        )

    def forward(
            self,
            viewpoint_camera: Camera,
            pc: MipSplattingModel,
            bg_color: torch.Tensor,
            scaling_modifier=1.0,
            render_types: list = None,
            **kwargs,
    ):
        if render_types is None:
            render_types = ["rgb"]
        
        opacities, scales = pc.get_3d_filtered_scales_and_opacities()
        projection_results = self.preprocess(pc=pc, viewpoint_camera=viewpoint_camera, scaling_modifier=scaling_modifier)
        xys, depths, radii, conics, comp, num_tiles_hit, cov3d = projection_results
        is_gaussian_visible = radii > 0

        rgb = None
        if "rgb" in render_types:
            rgb = self.renderer.render(
                means3D=pc.get_xyz,
                opacities=opacities,
                scales=scales,
                rotations=pc.get_rotation,
                features=pc.get_features,
                active_sh_degree=pc.active_sh_degree,
                viewpoint_camera=viewpoint_camera,
                bg_color=bg_color,
                scaling_modifier=scaling_modifier,
                anti_aliased=True,
                extra_projection_kwargs={
                    "filter_2d_kernel_size": self.config.filter_2d_kernel_size,
                }
            )["render"]
        
        inverse_depth_im = None
        if "inverse_depth" in render_types:
            inverse_depth = 1. / (depths.clamp_min(0.) + 1e-8).unsqueeze(-1)
            inverse_depth_im = self.renderer.rasterize_simplified(
                project_results=projection_results,
                viewpoint_camera=viewpoint_camera,
                colors=inverse_depth,
                bg_color=torch.zeros((1,), dtype=torch.float, device=bg_color.device),
                opacities=opacities,
                anti_aliased=False,  # already applied AA above
            )

        hard_inverse_depth_im = None
        if "hard_inverse_depth" in render_types:
            inverse_depth = 1. / (depths.clamp_min(0.) + 1e-8).unsqueeze(-1)
            hard_inverse_depth_im = self.renderer.rasterize_simplified(
                project_results=projection_results,
                viewpoint_camera=viewpoint_camera,
                colors=inverse_depth,
                bg_color=torch.zeros((1,), dtype=torch.float, device=bg_color.device),
                opacities=opacities + (1 - opacities.detach()),
                anti_aliased=False,  # already applied AA above
            )
        
        return {
            "render": rgb,
            "inverse_depth": inverse_depth_im,
            "hard_inverse_depth": hard_inverse_depth_im,
            "viewspace_points": xys,
            "viewspace_points_grad_scale": 0.5 * torch.tensor([[viewpoint_camera.width, viewpoint_camera.height]]).to(xys),
            "visibility_filter": is_gaussian_visible,
            "radii": radii,
        }
```
very appreciate for your nice work!
btw, if I want to participate in project development, what should I do?

**Comment by yzslab** [comment]
> ```python
>         rgb = None
>         if "rgb" in render_types:
>             rgb = self.renderer.render(
>                 means3D=pc.get_xyz,
>                 opacities=opacities,
>                 scales=scales,
>                 rotations=pc.get_rotation,
>                 features=pc.get_features,
>                 active_sh_degree=pc.active_sh_degree,
>                 viewpoint_camera=viewpoint_camera,
>                 bg_color=bg_color,
>                 scaling_modifier=scaling_modifier,
>                 anti_aliased=True,
>                 extra_projection_kwargs={
>                     "filter_2d_kernel_size": self.config.filter_2d_kernel_size,
>                 }
>             )["render"]
> ```


The rasterization of the rgb shoule use `self.renderer.rasterize_simplified()` too:
https://github.com/yzslab/gaussian-splatting-lightning/blob/739c5decc76f71bf43a99eeef0e070a46f8b84e1/internal/renderers/gsplat_appearance_embedding_renderer.py#L194-L201


  
  

> ```python
>     def preprocess(self, pc, viewpoint_camera, scaling_modifier):
>         return GSPlatRenderer.project(
>             means3D=pc.get_xyz,
>             scales=pc.get_scaling,
>             rotations=pc.get_rotation,
>             viewpoint_camera=viewpoint_camera,
>             scaling_modifier=scaling_modifier,
>         )
> ```

Please note that the `filter_2d_kernel_size` is required by MipSplatting:
https://github.com/yzslab/gaussian-splatting-lightning/blob/739c5decc76f71bf43a99eeef0e070a46f8b84e1/internal/renderers/gsplat_appearance_embedding_renderer.py#L297-L313

**Comment by yzslab** [comment]
I think you can simply use `GSplatAppearanceEmbeddingMipRenderer`. Simply replace these lines 
https://github.com/yzslab/gaussian-splatting-lightning/blob/739c5decc76f71bf43a99eeef0e070a46f8b84e1/internal/renderers/gsplat_appearance_embedding_renderer.py#L186-L192

with 

https://github.com/yzslab/gaussian-splatting-lightning/blob/739c5decc76f71bf43a99eeef0e070a46f8b84e1/internal/renderers/gsplat_renderer.py#L97-L99
