### ISSUE TITLE
appearance model 2DGS issue

### ISSUE THREAD

**Issue by hardikdava** [yzslab/gaussian-splatting-lightning#88]
Hello @yzslab :wave: , I am testing new appearance model with 2DGS renderer. I have trained my model with following command:

```
python main.py fit --config sh_view_dependent-2dgs.yaml --data.path data/scene_1
```

I was able to train the model but when i am trying to fuse colors using following command:

```
python utils/fuse_appearance_embeddings_into_shs_dc.py /path/to/trained_model.ckpt --output /output/path
```

But I am getting following error due to mismatch in scale size:

```
python3.10/site-packages/gsplat/cuda/_wrapper.py", line 297, in fully_fused_projection
    assert scales.size() == (N, 3), scales.size()
AssertionError: torch.Size([269488, 2])
```

This is due to only having 2 scales in the model. Any suggestion on how I can fix this. Thanks in advance.

**Comment by yzslab** [comment]
Fixing it requires implementing a 2DGS version of `GSplatHitPixelCountRenderer` in the cuda rasterizer.
You can try adding a `0` to the scales here, making it become `[N, 3]`, to see if it works:
https://github.com/yzslab/gaussian-splatting-lightning/blob/d39fcf6560f4513f48b9c8cc19f8c6b8d4c82281/utils/fuse_appearance_embeddings_into_shs_dc.py#L41

**Comment by hardikdava** [comment]
@yzslab That worked. But ran into OOM issue. I don't why I am using 24 GB nvidia 4090 graphic card. It was not the case earlier.

**Comment by yzslab** [comment]
> @yzslab That worked. But ran into OOM issue. I don't why I am using 24 GB nvidia 4090 graphic card. It was not the case earlier.

Try `--device cpu --camera-chunk-size 1`.

**Comment by hardikdava** [comment]
@yzslab Tried it with your suggestion but did not work.

**Comment by yzslab** [comment]
> @yzslab Tried it with your suggestion but did not work.

Please post the exception outputs here.

**Comment by hardikdava** [comment]
```
loading appearance groups from data/bed_colmap/appearance_groups
loading colmap 3D points
[colmap dataparser] train set images: 360, val set images: 45, loaded mask: 0
Traceback (most recent call last):                                                                                                           
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/utils/fuse_appearance_embeddings_into_shs_dc.py", line 368, in <module>
    main()
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/utils/fuse_appearance_embeddings_into_shs_dc.py", line 350, in main
    gaussian_model = fuse(
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/utils/fuse_appearance_embeddings_into_shs_dc.py", line 266, in fuse
    _, visibility_score_pruned_sorted_indices, visibility_score_pruned_top_k_pdf = prune_and_get_weights(
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/utils/fuse_appearance_embeddings_into_shs_dc.py", line 64, in prune_and_get_weights
    visibility_score = calculate_gaussian_scores(cameras, gaussian_model, "cpu").T  # [N_gaussians, N_cameras]
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/utils/fuse_appearance_embeddings_into_shs_dc.py", line 38, in calculate_gaussian_scores
    hit_count, opacity_score, alpha_score, visibility_score = GSplatHitPixelCountRenderer.hit_pixel_count(
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/internal/renderers/gsplat_hit_pixel_count_renderer.py", line 34, in hit_pixel_count
    count, opacity_score, alpha_score, visibility_score = hit_pixel_count(
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/venv/lib/python3.10/site-packages/gsplat/v0_interfaces.py", line 518, in hit_pixel_count
    tiles_per_gauss, isect_ids, flatten_ids = wrapper.isect_tiles(
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/venv/lib/python3.10/site-packages/gsplat/cuda/_wrapper.py", line 400, in isect_tiles
    tiles_per_gauss, isect_ids, flatten_ids = _make_lazy_cuda_func("isect_tiles")(
  File "/home/Desktop/yzlab/gaussian-splatting-lightning/venv/lib/python3.10/site-packages/gsplat/cuda/_wrapper.py", line 14, in call_cuda
    return getattr(_C, name)(*args, **kwargs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.46 GiB (GPU 0; 23.69 GiB total capacity; 254.25 MiB already allocated; 21.35 GiB free; 336.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by yzslab** [comment]
@hardikdava  and your modification: `git --no-pager diff utils/fuse_appearance_embeddings_into_shs_dc.py`

**Comment by hardikdava** [comment]
I have selected scale_2 value to be `1e-6` based on suggested by 2dgs author. 

```
diff --git a/utils/fuse_appearance_embeddings_into_shs_dc.py b/utils/fuse_appearance_embeddings_into_shs_dc.py
index ce1e0fe..1e57e91 100644
--- a/utils/fuse_appearance_embeddings_into_shs_dc.py
+++ b/utils/fuse_appearance_embeddings_into_shs_dc.py
@@ -249,6 +249,13 @@ def fuse(
         ckpt,
         cuda_device,
     )
+    if gaussian_model.get_scaling.shape[1] == 2:
+        scales = gaussian_model.scales
+        third_column = torch.full((scales.size(0), 1), 1e-6).to(device=scales.device)
+        # Concatenate the new column to the original tensor
+        gaussian_model.scales = torch.cat((scales, third_column), dim=1)
+        del third_column 
+        del scales
     # prune those outside bounding box
     gaussian_model.to(device=cuda_device)
     # get renderer

```

**Comment by yzslab** [comment]
> gaussian_model.scales

The `scales = ...` should be `scales = gaussian_model.get_scales()`.

**Comment by yzslab** [comment]
@hardikdava 

Ignore what I said in the comment above.

The problem should be the `1e-6`. Try `torch.full((scales.size(0), 1), gaussian_model.scale_inverse_activation(1e-6))`

**Comment by hardikdava** [comment]
Thanks. This is final work around for 2DGS.

```
 if gaussian_model.get_scaling.shape[1] == 2:
        scales = gaussian_model.scales
        tensor_value = torch.tensor(1e-6)
        third_column = torch.full((scales.size(0), 1), gaussian_model.scale_inverse_activation(tensor_value)).to(scales.device)
        # Concatenate the new column to the original tensor
        gaussian_model.scales = torch.cat((scales, third_column), dim=1)
        del third_column 
        del scales
```

**Comment by hardikdava** [comment]
@yzslab Thanks for your help.
