### ISSUE TITLE
CUDA Error About ‘raddi‘

### ISSUE THREAD

**Issue by lzt02** [yzslab/gaussian-splatting-lightning#95]
Hello, it's a very meaningful job. 
I encountered a problem while using the visual UI (python viewer.py output/splat.py). Specifically, when I moved the camera, an error was triggered:
```
error occurred when rendering for client
Traceback (most recent call last):
  File "gaussian-splatting-lightning/internal/viewer/client.py", line 145, in run
    self.render_and_send()
  File "gaussian-splatting-lightning/internal/viewer/client.py", line 113, in render_and_send
    image = self.renderer.get_outputs(camera, scaling_modifier=self.viewer.scaling_modifier.value)
  File "gaussian-splatting-lightning/internal/viewer/renderer.py", line 124, in get_outputs
    render_outputs = self.renderer(
  File "conda_envs/gspl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "gaussian-splatting-lightning/internal/renderers/vanilla_renderer.py", line 128, in forward
    "visibility_filter": radii > 0,
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
I conducted some tests and found that when the invisible gs area is large, many values in radii are 0, which will stably trigger this error.
Hope to receive your assistance.

**Comment by yzslab** [comment]
There are many reasons for this problem.

Are you viewing a ply file? If yes, a simple workaround is switching to gsplat.
1. Pull the latest version (I pushed a new commit just now).
2. Install the gsplat v1 by following this guide: https://github.com/yzslab/gaussian-splatting-lightning?tab=readme-ov-file#15-install-optional-packages
3. Start the viewer using this: `python viewer.py YOUR_PLY_FILE --gsplat`.

It is equivalent to diff-gaussian-rasterization.

**Comment by lzt02** [comment]
Thanks for your help! This worked,  now I can use the UI without any hindrance.

However, I encountered the same error when executing `python render.py output/splat.ply --camera-path-filename camera_paths/2024-12-13-15-14-59.json --output-path renders//2024-12-13-15-14-59.mp4`:
```
Traceback (most recent call last):
  File "/home/hugoycj/PrivateStorage4/dataset/3DG100K/extracted/ziteng/gaussian-splatting-lightning/render.py", line 278, in <module>
    render_frames(
  File "/home/hugoycj/PrivateStorage4/dataset/3DG100K/extracted/ziteng/gaussian-splatting-lightning/render.py", line 213, in render_frames
    image = viewer_renderer.get_outputs(camera).cpu()
  File "/home/hugoycj/PrivateStorage4/dataset/3DG100K/extracted/ziteng/gaussian-splatting-lightning/internal/viewer/renderer.py", line 124, in get_outputs
    render_outputs = self.renderer(
  File "/home/ziteng/anaconda3/envs/gspl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hugoycj/PrivateStorage4/dataset/3DG100K/extracted/ziteng/gaussian-splatting-lightning/internal/renderers/vanilla_renderer.py", line 127, in forward
    "visibility_filter": radii > 0,
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
```
Hope to receive your assistance again.

**Comment by lzt02** [comment]
> There are many reasons for this problem.
> 
> Are you viewing a ply file? If yes, a simple workaround is switching to gsplat.
> 
> 1. Pull the latest version (I pushed a new commit just now).
> 2. Install the gsplat v1 by following this guide: https://github.com/yzslab/gaussian-splatting-lightning?tab=readme-ov-file#15-install-optional-packages
> 3. Start the viewer using this: `python viewer.py YOUR_PLY_FILE --gsplat`.
> 
> It is equivalent to diff-gaussian-rasterization.


Thanks for your help! This worked,  now I can use the UI without any hindrance.

However, I encountered the same error when executing `python render.py output/splat.ply --camera-path-filename camera_paths/2024-12-13-15-14-59.json --output-path renders//2024-12-13-15-14-59.mp4`:
```
Traceback (most recent call last):
  File "/home/hugoycj/PrivateStorage4/dataset/3DG100K/extracted/ziteng/gaussian-splatting-lightning/render.py", line 278, in <module>
    render_frames(
  File "/home/hugoycj/PrivateStorage4/dataset/3DG100K/extracted/ziteng/gaussian-splatting-lightning/render.py", line 213, in render_frames
    image = viewer_renderer.get_outputs(camera).cpu()
  File "/home/hugoycj/PrivateStorage4/dataset/3DG100K/extracted/ziteng/gaussian-splatting-lightning/internal/viewer/renderer.py", line 124, in get_outputs
    render_outputs = self.renderer(
  File "/home/ziteng/anaconda3/envs/gspl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hugoycj/PrivateStorage4/dataset/3DG100K/extracted/ziteng/gaussian-splatting-lightning/internal/renderers/vanilla_renderer.py", line 127, in forward
    "visibility_filter": radii > 0,
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
```
Hope to receive your assistance again.

**Comment by yzslab** [comment]
> However, I encountered the same error when executing `python render.py output/splat.ply --camera-path-filename camera_paths/2024-12-13-15-14-59.json --output-path renders//2024-12-13-15-14-59.mp4`

Try this patch:
```diff
diff --git a/render.py b/render.py
index 99d4c7b..1b14297 100644
--- a/render.py
+++ b/render.py
@@ -241,6 +241,9 @@ if __name__ == "__main__":
 
         renderer_override = Vanilla2DGSRenderer()
 
+    from internal.renderers.gsplat_v1_renderer import GSplatV1Renderer
+    renderer_override = GSplatV1Renderer().instantiate()
+
     # instantiate renderer
     # TODO: set output type
     renderer = initializer_viewer_renderer(
```

**Comment by yzslab** [comment]
Hi, I forgot to set the `anti_aliased` to `False` in the comment above.

Here the correct one:
```diff
diff --git a/render.py b/render.py
index 99d4c7b..0e5da77 100644
--- a/render.py
+++ b/render.py
@@ -241,6 +241,9 @@ if __name__ == "__main__":
 
         renderer_override = Vanilla2DGSRenderer()
 
+    from internal.renderers.gsplat_v1_renderer import GSplatV1Renderer
+    renderer_override = GSplatV1Renderer(anti_aliased=False).instantiate()
+
     # instantiate renderer
     # TODO: set output type
     renderer = initializer_viewer_renderer(
diff

**Comment by lzt02** [comment]
> Hi, I forgot to set the `anti_aliased` to `False` in the comment above.
> 
> Here the correct one:
> 
> ```diff
> diff --git a/render.py b/render.py
> index 99d4c7b..0e5da77 100644
> --- a/render.py
> +++ b/render.py
> @@ -241,6 +241,9 @@ if __name__ == "__main__":
>  
>          renderer_override = Vanilla2DGSRenderer()
>  
> +    from internal.renderers.gsplat_v1_renderer import GSplatV1Renderer
> +    renderer_override = GSplatV1Renderer(anti_aliased=False).instantiate()
> +
>      # instantiate renderer
>      # TODO: set output type
>      renderer = initializer_viewer_renderer(
> diff
> ```

The code works, thanks for your detailed help!
