### ISSUE TITLE
Fuse appearance embeddings is failing

### ISSUE THREAD

**Issue by earth-bass** [yzslab/gaussian-splatting-lightning#96]
```
-01_-03:   0%|                                                                  | 0/19 [00:24<?, ?it/s, Loading colmap model...]loading appearance groups from /splat/appearance_image_dedicated
down sample enabled
generate 100000 random points
[colmap dataparser] train set images: 1963, val set images: 31, loaded mask: 0
-01_-03:   0%|                                                                                | 0/19 [00:32<?, ?it/s, Fusing...]
Traceback (most recent call last):                                                                                              
  File "/home/matth/gaussian-splatting-lightning/utils/merge_partitions_v2.py", line 260, in <module>
    main()
  File "/home/matth/gaussian-splatting-lightning/utils/merge_partitions_v2.py", line 201, in main
    fuse_appearance_features(
  File "/home/matth/gaussian-splatting-lightning/utils/merge_partitions_v2.py", line 60, in fuse_appearance_features
    rgb_offset = average_embedding_fusing(
  File "/home/matth/gaussian-splatting-lightning/env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/matth/gaussian-splatting-lightning/utils/fuse_appearance_embeddings_into_shs_dc.py", line 178, in average_embedding_fusing
    appearance_embeddings = renderer.model.embedding(appearance_ids).reshape((
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 32, -1] because the unspecified dimension size -1 can be any value and is ambiguous
```

**Comment by yzslab** [comment]
Looks like there are no Gaussians in this partition `-01_-03`.
Is this a pruned and finetuned partition?
Can `viewer.py` render this partition correctly?
Please append a `print(gaussian_to_preserve.shape, gaussian_to_preserve.sum())` to [here](https://github.com/yzslab/gaussian-splatting-lightning/blob/9d1dd483bf12d13dc139d18160dcc77717ac4491/utils/fuse_appearance_embeddings_into_shs_dc.py#L75) , then see what it prints.
